swagger: '2.0'

info:
  version: "2.0.0"
  title: MailHog API

definitions:
  jim:
    type: object
    properties:
      DisconnectChance:
        type: number
        format: float
        description: Chance of randomly disconnecting a session
      AcceptChance:
        type: number
        format: float
        description: Chance of accepting an incoming connection
      LinkSpeedAffect:
        type: number
        format: float
        description: Chance of applying a rate limit
      LinkSpeedMin:
        type: number
        format: float
        description: Minimum link speed (in bytes per second)
      LinkSpeedMax:
        type: number
        format: float
        description: Maximum link speed (in bytes per second)
      RejectSenderChance:
        type: number
        format: float
        description: Chance of rejecting a MAIL FROM command
      RejectRecipientChance:
        type: number
        format: float
        description: Chance of rejecting a RCPT TO command
      RejectAuthChance:
        type: number
        format: float
        description: Chance of rejecting an AUTH command

paths:
  /api/v2/jim:
    get:
      description: |
        Get Jim's configuration
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/jim'
        '404':
          description: Jim is not enabled
    post:
      description: |
        Enable Jim
      parameters:
        - 
          name: 'config'
          in: body
          schema:
            $ref: '#/definitions/jim'
      responses:
        '200':
          description: Successful response
        '400':
          description: Jim is already enabled
    put:
      description: |
        Update Jim
      parameters:
        - 
          name: 'config'
          in: body
          schema:
            $ref: '#/definitions/jim'
      responses:
        '200':
          description: Successful response
        '404':
          description: Jim is not enabled
    delete:
      description: |
        Disable Jim
      responses:
        '200':
          description: Successful response
        '404':
          description: Jim is not enabled
  /api/v2/messages:
    get:
      description: |
        Retrieve a list of messages
      parameters:
        -
          name: start
          in: query
          description: Start index
          required: false
          type: number
          format: int64
          default: 0
        -
          name: limit
          in: query
          description: Number of messages
          required: false
          type: number
          format: int64
          default: 50
      responses:
        200:
          description: Successful response
          schema:
            title: Messages
            type: object
            properties:
              total:
                type: number
                format: int64
                description: Total number of stored messages
              start:
                type: number
                format: int64
                description: Start index of first returned message
              count:
                type: number
                format: int64
                description: Number of returned messages
              messages:
                type: array
                items:
                  title: Message
                  type: object
                  properties:
                    id:
                      type: string
                    from:
                      title: Path
                      type: object
                      properties:
                        relays:
                          type: array
                          items:
                            type: string
                        mailbox:
                          type: string
                        domain:
                          type: string
                        params:
                          type: string
                    to:
                      type: array
                      items:
                        title: Path
                        type: object
                        properties:
                          relays:
                            type: array
                            items:
                              type: string
                          mailbox:
                            type: string
                          domain:
                            type: string
                          params:
                            type: string
                    headers:
                      type: object
                    size:
                      type: number
                      format: int64
                    created:
                      type: string
                      format: date-time
  /api/v2/search:
    get:
      description: |
        Search messages
      parameters:
        -
          name: kind
          in: query
          description: Kind of search
          required: true
          type: string
          enum: [ from, to, containing ]
        -
          name: query
          in: query
          description: Search parameter
          required: true
          type: string
        -
          name: start
          in: query
          description: Start index
          required: false
          type: number
          format: int64
          default: 0
        -
          name: limit
          in: query
          description: Number of messages
          required: false
          type: number
          format: int64
          default: 50
      responses:
        200:
          description: Successful response
          schema:
            title: Messages
            type: object
            properties:
              total:
                type: number
                format: int64
                description: Total number of stored messages
              start:
                type: number
                format: int64
                description: Start index of first returned message
              count:
                type: number
                format: int64
                description: Number of returned messages
              messages:
                type: array
                items:
                  title: Message
                  type: object
                  properties:
                    id:
                      type: string
                    from:
                      title: Path
                      type: object
                      properties:
                        relays:
                          type: array
                          items:
                            type: string
                        mailbox:
                          type: string
                        domain:
                          type: string
                        params:
                          type: string
                    to:
                      type: array
                      items:
                        title: Path
                        type: object
                        properties:
                          relays:
                            type: array
                            items:
                              type: string
                          mailbox:
                            type: string
                          domain:
                            type: string
                          params:
                            type: string
                    headers:
                      type: object
                    size:
                      type: number
                      format: int64
                    created:
                      type: string
                      format: date-time
